import { ScriptConfig } from "../types";

// Helper to convert Hex to [r,g,b] array string for AE
const hexToAeColor = (hex: string): string => {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return `[${r.toFixed(3)}, ${g.toFixed(3)}, ${b.toFixed(3)}]`;
};

export const generateAeScript = (config: ScriptConfig): string => {
  const activeColorArr = hexToAeColor(config.textColor);
  const inactiveColorArr = hexToAeColor(config.inactiveColor);

  // We are embedding the script logic inside a template literal.
  // Note: We use \\n inside strings to ensure they appear as \n in the generated file's string literals.
  
  return `/**
 * AM歌词助手 v0.2
 * Generated by H2A-＆哈基米3 (Web Configured)
 */

{
    function LyricalAEScript(thisObj) {
        var scriptName = "AM歌词助手 v0.2";
        
        // --- CONFIGURATION ---
        var cfg = {
            compName: "${config.compName}",
            width: ${config.width},
            height: ${config.height},
            fps: ${config.fps},
            duration: ${config.duration},
            fontSize: ${config.fontSize},
            font: "${config.fontName}",
            textColor: ${activeColorArr}, // Active
            inactiveColor: ${inactiveColorArr}, // Inactive (Gray)
            spacing: ${config.spacing},
            blurMax: ${config.blurMax},
            activeScale: ${config.activeScale},
            damping: ${config.damping},
            alignment: "${config.alignment}",
            textLift: ${config.textLift}
        };

        // --- HELPER: COLOR CONVERSION ---
        function rgbToHexInt(r, g, b) {
            return (Math.round(r * 255) << 16) | (Math.round(g * 255) << 8) | Math.round(b * 255);
        }

        function hexIntToRgb(hex) {
            var r = ((hex >> 16) & 0xFF) / 255;
            var g = ((hex >> 8) & 0xFF) / 255;
            var b = (hex & 0xFF) / 255;
            return [r, g, b];
        }

        // --- UI BUILDER ---
        function buildUI(thisObj) {
            var win = (thisObj instanceof Panel) ? thisObj : new Window("palette", scriptName, undefined, {resizeable: true});
            win.orientation = "column";
            win.alignChildren = ["fill", "top"];
            win.spacing = 10;
            win.margins = 16;

            // --- HEADER ---
            var grpHeader = win.add("group");
            grpHeader.orientation = "column";
            grpHeader.alignChildren = ["left", "center"];
            var titleText = grpHeader.add("statictext", undefined, "AM 歌词生成器");
            titleText.graphics.font = ScriptUI.newFont("Arial", "BOLD", 16);
            grpHeader.add("statictext", undefined, "1. 导入LRC  2. 设置样式  3. 生成");

            var sep1 = win.add("panel", undefined, undefined);
            sep1.alignment = "fill";

            // --- STYLE SETTINGS (Color & Font) ---
            var pnlStyle = win.add("panel", undefined, "样式设置");
            pnlStyle.orientation = "column";
            pnlStyle.alignChildren = ["fill", "top"];
            pnlStyle.margins = 10;

            // 1. Color Picker
            var grpColor = pnlStyle.add("group");
            grpColor.orientation = "row";
            grpColor.add("statictext", undefined, "高亮颜色:");
            
            var btnColor = grpColor.add("button", undefined, "点击修改颜色...");
            btnColor.preferredSize.width = 120;
            
            // Color Preview Box
            var colorPreview = grpColor.add("group");
            colorPreview.preferredSize = [25, 25];
            
            function updateColorPreview() {
                var g = colorPreview.graphics;
                var brush = g.newBrush(g.BrushType.SOLID_COLOR, cfg.textColor);
                g.backgroundColor = brush;
                try {
                    colorPreview.notify("onDraw"); // Force redraw if possible
                } catch(e){}
            }
            // Initial draw handler
            colorPreview.onDraw = function() {
                var g = this.graphics;
                g.rectPath(0,0, this.size.width, this.size.height);
                g.fillPath(g.newBrush(g.BrushType.SOLID_COLOR, cfg.textColor));
            }

            btnColor.onClick = function() {
                var currentHex = rgbToHexInt(cfg.textColor[0], cfg.textColor[1], cfg.textColor[2]);
                var newHex = $.colorPicker(currentHex);
                if (newHex !== -1) {
                    cfg.textColor = hexIntToRgb(newHex);
                    updateColorPreview();
                    colorPreview.hide(); colorPreview.show(); // Force UI refresh
                }
            };

            // 2. Font Selector
            var grpFont = pnlStyle.add("group");
            grpFont.orientation = "row";
            grpFont.alignChildren = ["left", "center"];
            grpFont.add("statictext", undefined, "字体选择:");

            var fontDropdown = grpFont.add("dropdownlist", undefined, ["点击加载已安装字体..."]);
            fontDropdown.preferredSize.width = 180;
            fontDropdown.selection = 0;
            
            var fontsLoaded = false;
            var systemFonts = [];

            fontDropdown.onClick = function() {
                if (!fontsLoaded) {
                    fontDropdown.removeAll();
                    fontDropdown.add("item", "正在加载...");
                    fontDropdown.selection = 0;
                    
                    // Defer execution slightly to allow UI update
                    var task = function() {
                        fontDropdown.removeAll();
                        // Add default first
                        var defItem = fontDropdown.add("item", cfg.font);
                        fontDropdown.selection = defItem;

                        // Add system fonts
                        var all = app.fonts.allFonts;
                        // Limit to first 200 to prevent crash on systems with thousands of fonts, 
                        // or just add them all if user is patient.
                        // We will filter for common ones or just add all.
                        for (var i = 0; i < all.length; i++) {
                             // Use postScriptName for stability
                             var fname = all[i].postScriptName;
                             if (fname !== cfg.font) {
                                 fontDropdown.add("item", fname);
                             }
                        }
                        fontsLoaded = true;
                    };
                    // Schedule (fake schedule, ScriptUI blocks, but this is best effort)
                    task();
                }
            };

            fontDropdown.onChange = function() {
                if (fontDropdown.selection) {
                    cfg.font = fontDropdown.selection.text;
                }
            };

            // --- FILE & BUILD ---
            var pnlAction = win.add("panel", undefined, "生成操作");
            pnlAction.orientation = "column";
            pnlAction.alignChildren = ["fill", "top"];

            var btnGroup = pnlAction.add("group");
            btnGroup.orientation = "row";
            var btnImport = btnGroup.add("button", undefined, "1. 选择 LRC 文件");
            var stPath = btnGroup.add("statictext", undefined, "未选择", {truncate: "middle"});
            stPath.preferredSize.width = 150;

            var btnBuild = pnlAction.add("button", undefined, "2. 生成歌词序列");
            btnBuild.enabled = false;
            
            var progressBar = pnlAction.add("progressbar", undefined, 0, 100);
            progressBar.preferredSize.width = 300;
            progressBar.visible = false;

            var lrcFile = null;

            btnImport.onClick = function() {
                var f = File.openDialog("请选择 LRC 文件", "*.lrc;*.txt");
                if (f) {
                    lrcFile = f;
                    stPath.text = f.name;
                    btnBuild.enabled = true;
                }
            };

            btnBuild.onClick = function() {
                if (!lrcFile || !lrcFile.exists) {
                    alert("请选择有效的 LRC 文件。");
                    return;
                }
                
                app.beginUndoGroup("LyricalAE 生成");
                try {
                    progressBar.visible = true;
                    progressBar.value = 0;
                    
                    lrcFile.open("r");
                    lrcFile.encoding = "UTF-8";
                    var content = lrcFile.read();
                    lrcFile.close();
                    
                    var lines = parseLrc(content);
                    if (lines.length === 0) {
                        alert("未找到有效的歌词行。请检查文件格式。");
                        return;
                    }
                    
                    var comp = app.project.items.addComp(cfg.compName, cfg.width, cfg.height, 1, cfg.duration, cfg.fps);
                    comp.openInViewer();
                    
                    var ctrl = comp.layers.addNull();
                    ctrl.name = "Controller (控制层)";
                    
                    var slider = ctrl.property("ADBE Effect Parade").addProperty("ADBE Slider Control");
                    slider.name = "Scroll Y";
                    
                    createLyricLayers(comp, lines, ctrl, progressBar);
                    
                    progressBar.value = 100;
                    alert("成功！已生成 " + lines.length + " 行歌词。");
                } catch(e) {
                    alert("发生错误: " + e.toString() + "\\n行号: " + e.line);
                } finally {
                    app.endUndoGroup();
                    progressBar.visible = false;
                }
            };

            win.layout.layout(true);
            return win;
        }

        function parseLrc(text) {
            var lines = text.split(/(\\r\\n|\\r|\\n)/);
            var result = [];
            var regex = /\\[(\\d{2}):(\\d{2})\\.(\\d{2,3})\\](.*)/;
            
            for (var i = 0; i < lines.length; i++) {
                var match = lines[i].match(regex);
                if (match) {
                    var mins = parseInt(match[1], 10);
                    var secs = parseInt(match[2], 10);
                    var ms = parseInt(match[3], 10);
                    if (match[3].length === 2) ms *= 10;
                    
                    var time = mins * 60 + secs + (ms / 1000);
                    var txt = match[4].replace(/^\\s+|\\s+$/g, '');
                    
                    if (txt.length > 0) {
                        result.push({time: time, text: txt});
                    }
                }
            }
            return result;
        }

        function createLyricLayers(comp, lines, ctrl, pb) {
            var activeIndexProp = ctrl.property("ADBE Effect Parade").property("Scroll Y").property("ADBE Slider Control-0001");

            // Setup Keys for Active Index
            for (var i = 0; i < lines.length; i++) {
                var t = lines[i].time;
                var keyIndex = activeIndexProp.addKey(t);
                activeIndexProp.setValueAtKey(keyIndex, i);
                activeIndexProp.setInterpolationTypeAtKey(keyIndex, KeyframeInterpolationType.HOLD, KeyframeInterpolationType.HOLD);
            }

            // Create Smooth Index
            var smoothEffect = ctrl.property("ADBE Effect Parade").addProperty("ADBE Slider Control");
            smoothEffect.name = "Smooth Index";
            var smoothSliderProp = smoothEffect.property("ADBE Slider Control-0001");
            
            // CHANGED: Use Exponential Decay based on Damping config. 
            // Damping (0.1 - 2.0) controls the speed. Higher damping = faster settle (higher decay constant).
            // Multiplier 8.0 gives a good range (0.8 -> ~6.4, 2.0 -> 16.0).
            var bounceExpr = 
                "var decay = " + (cfg.damping * 8.0) + ";\\n" + 
                "var n = 0;\\n" +
                "var t = 0;\\n" +
                "var activeVal = thisComp.layer('" + ctrl.name + "').effect('Scroll Y')('ADBE Slider Control-0001');\\n" +
                "if (activeVal.numKeys > 0) {\\n" +
                "  n = activeVal.nearestKey(time).index;\\n" +
                "  if (activeVal.key(n).time > time) n--;\\n" +
                "}\\n" +
                "if (n <= 0) {\\n" +
                "  t = 0;\\n" +
                "} else {\\n" +
                "  t = time - activeVal.key(n).time;\\n" +
                "}\\n" +
                "if (n > 0) {\\n" +
                "  var val = activeVal.value;\\n" +
                "  var prevVal = (n > 1) ? activeVal.key(n-1).value : 0;\\n" +
                "  var diff = val - prevVal;\\n" +
                "  // Exponential ease-out (NO BOUNCE)\\n" +
                "  val - diff / Math.exp(t * decay);\\n" +
                "} else {\\n" +
                "  activeVal.value;\\n" +
                "}";
            
            smoothSliderProp.expression = bounceExpr;

            var spacing = cfg.spacing;
            var isLeft = (cfg.alignment === "left");
            var xPos = isLeft ? (comp.width * 0.1) : (comp.width / 2);
            var yCenter = comp.height / 2; 

            for (var i = 0; i < lines.length; i++) {
                var l = lines[i];
                var tStart = l.time;
                var tEnd = (i < lines.length - 1) ? lines[i+1].time : (l.time + 5.0);
                
                var tLayer = comp.layers.addText(l.text);
                var tProp = tLayer.property("ADBE Text Properties").property("ADBE Text Document");
                var tDoc = tProp.value;
                
                tDoc.fontSize = cfg.fontSize;
                tDoc.fillColor = cfg.inactiveColor; 
                tDoc.justification = isLeft ? ParagraphJustification.LEFT_JUSTIFY : ParagraphJustification.CENTER_JUSTIFY;
                try { tDoc.font = cfg.font; } catch (e) {}
                tProp.setValue(tDoc);
                
                tLayer.property("ADBE Transform Group").property("ADBE Position").setValue([xPos, yCenter]);
                tLayer.property("ADBE Transform Group").property("ADBE Anchor Point").setValue([0, 0]); 

                // --- ANIMATOR (Fill & Lift) ---
                var textGroup = tLayer.property("ADBE Text Properties");
                var animators = textGroup.property("ADBE Text Animators");
                var animGroup = animators.addProperty("ADBE Text Animator");
                animGroup.name = "Highlight Animator";
                
                var animProps = animGroup.property("ADBE Text Animator Properties");
                
                var fillProp = animProps.addProperty("ADBE Text Fill Color");
                fillProp.setValue(cfg.textColor);

                var posProp = null;
                try { posProp = animProps.addProperty("ADBE Text Position"); } catch(e) {}
                if (!posProp) {
                     try { posProp = animProps.addProperty("ADBE Text Position 3D"); } catch(e) {}
                }
                
                if (posProp) {
                    if (posProp.value.length === 3) {
                         posProp.setValue([0, -cfg.textLift, 0]);
                    } else {
                         posProp.setValue([0, -cfg.textLift]);
                    }
                }
                
                var selectors = animGroup.property("ADBE Text Selectors");
                while (selectors.numProperties > 0) {
                    selectors.property(1).remove();
                }

                var rangeSelector = selectors.addProperty("ADBE Text Selector");
                var endProp = rangeSelector.property("ADBE Text Percent End");
                
                var fillExpr = 
                    "ease(time, " + tStart + ", " + tEnd + ", 0, 100);";
                endProp.expression = fillExpr;

                // --- TRANSFORM EXPRESSIONS ---
                var posExpr = 
                    "var idx = " + i + ";\\n" +
                    "var activeIdx = thisComp.layer('" + ctrl.name + "').effect('Smooth Index')('ADBE Slider Control-0001');\\n" +
                    "var diff = idx - activeIdx;\\n" +
                    "value + [0, diff * " + spacing + "];";
                tLayer.property("ADBE Transform Group").property("ADBE Position").expression = posExpr;
                
                var scaleExpr = 
                    "var idx = " + i + ";\\n" +
                    "var activeIdx = thisComp.layer('" + ctrl.name + "').effect('Smooth Index')('ADBE Slider Control-0001');\\n" +
                    "var diff = Math.abs(idx - activeIdx);\\n" +
                    "var s = linear(diff, 0, 0.8, " + (cfg.activeScale * 100) + ", 100);\\n" +
                    "[s, s];";
                tLayer.property("ADBE Transform Group").property("ADBE Scale").expression = scaleExpr;
                
                var opExpr = 
                    "var idx = " + i + ";\\n" +
                    "var activeIdx = thisComp.layer('" + ctrl.name + "').effect('Smooth Index')('ADBE Slider Control-0001');\\n" +
                    "var diff = Math.abs(idx - activeIdx);\\n" +
                    "linear(diff, 1.0, 3.5, 100, " + 50 + ");";
                tLayer.property("ADBE Transform Group").property("ADBE Opacity").expression = opExpr;
                
                var blurEff = tLayer.property("ADBE Effect Parade").addProperty("ADBE Gaussian Blur 2");
                blurEff.name = "Blur";
                var blurProp = blurEff.property("ADBE Gaussian Blur 2-0001");
                
                var blurExpr = 
                    "var idx = " + i + ";\\n" +
                    "var activeIdx = thisComp.layer('" + ctrl.name + "').effect('Smooth Index')('ADBE Slider Control-0001');\\n" +
                    "var diff = Math.abs(idx - activeIdx);\\n" +
                    "(diff < 0.3) ? 0 : " + cfg.blurMax + ";";
                blurProp.expression = blurExpr;

                if (pb) pb.value = (i / lines.length) * 100;
            }
        }

        var win = buildUI(thisObj);
        if (win instanceof Window) {
            win.center();
            win.show();
        } else {
            win.layout.layout(true);
        }
    }
    LyricalAEScript(this);
}
`;
};